sonar.projectKey=oc-bobapp-back
sonar.organization=visualdev-fr

# relative paths to source directories. More details and properties are described
# at https://docs.sonarsource.com/sonarqube-cloud/advanced-setup/analysis-scope/
sonar.projectName=oc-bobapp-back
sonar.sources=src/main
sonar.java.source=11
sonar.junit.reportPaths=target/surefire-reports
sonar.jacoco.reportPaths=target/jacoco.exec
sonar.host.url=https://sonarcloud.io
sonar.token=${env.SONAR_TOKEN_BACK}
sonar.java.binaries=target/classes
sonar.project.monorepo.enabled=true