name: Test & Deploy BobApp - Front
run-name: build, test, scan, and publish the frontend

on:
  push:
    branches:
    - 'main'
  workflow_dispatch:

jobs:

  build-and-test:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Disabling shallow clones is recommended for improving the relevancy of reporting

      - name: setup frontend
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: front/package-lock.json
          node-version: '16'
          cache: 'npm'

      - name: test frontend
        working-directory: front
        run: npm install && npm run test -- --code-coverage --browsers=ChromeHeadless --watch=false

      - name: Create code coverage Summary
        uses: irongut/CodeCoverageSummary@v1.3.0
        id: coverage-report-frontend
        with:
          filename: front/coverage/bobapp/cobertura-coverage.xml
          badge: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: "80 100"

      - name: Add coverage report in the action summary
        run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY

      - name: upload frontend coverage report
        uses: actions/upload-artifact@v4
        with:
          name: karma-report
          path: front/coverage

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5.1.0
        with:
          projectBaseDir: front
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_FRONT }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  publish-docker-images:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push front-end image
        uses: docker/build-push-action@v6
        with:
          context: front
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bobapp-front:latest
